"""最適化ジョブのテーブルを作る

Revision ID: 91f23f00db24
Revises: 349661cfca00
Create Date: 2026-09-13 03:44:16.847261
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "91f23f00db24"
down_revision: str | None = "349661cfca00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "optimization_jobs",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params_key", sa.String(length=64), nullable=False),
        sa.Column("engine_revision", sa.String(length=16), nullable=False),
        sa.Column("strategy", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=True),
        sa.Column("detail", sa.String(length=255), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_optimization_jobs_params_key", "optimization_jobs", ["params_key"], unique=False
    )
    op.create_index(
        "ix_optimization_jobs_status_created_at",
        "optimization_jobs",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_optimization_jobs_status_created_at", table_name="optimization_jobs")
    op.drop_index("ix_optimization_jobs_params_key", table_name="optimization_jobs")
    op.drop_table("optimization_jobs")
    # ### end Alembic commands ###
