"""ジョブに速さと進み具合を持たせ、ワーカーの速さを残す

Revision ID: d1b73a3b4a54
Revises: 91f23f00db24
Create Date: 2026-09-14 05:49:21.419288
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d1b73a3b4a54"
down_revision: str | None = "91f23f00db24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_speeds",
        sa.Column("games_per_second", sa.Float(), nullable=False),
        sa.Column("threads", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("optimization_jobs", sa.Column("games_per_second", sa.Float(), nullable=True))
    op.add_column("optimization_jobs", sa.Column("work_done", sa.Integer(), nullable=True))
    op.add_column("optimization_jobs", sa.Column("work_total", sa.Integer(), nullable=True))
    op.add_column("optimization_jobs", sa.Column("remaining_seconds", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("optimization_jobs", "remaining_seconds")
    op.drop_column("optimization_jobs", "work_total")
    op.drop_column("optimization_jobs", "work_done")
    op.drop_column("optimization_jobs", "games_per_second")
    op.drop_table("worker_speeds")
    # ### end Alembic commands ###
